#pragma once

#define DISTRHO_PLUGIN_NAME "CWS80 wave synthesizer"
#define DISTRHO_PLUGIN_NUM_INPUTS 0
#define DISTRHO_PLUGIN_NUM_OUTPUTS 2
#define DISTRHO_PLUGIN_URI "http://jpcima.sdf1.org/lv2/cws80"
#define DISTRHO_PLUGIN_HAS_UI 1
#define DISTRHO_PLUGIN_IS_RT_SAFE 1
#define DISTRHO_PLUGIN_IS_SYNTH 1
#define DISTRHO_PLUGIN_WANT_DIRECT_ACCESS 1
#define DISTRHO_PLUGIN_WANT_LATENCY 0
#define DISTRHO_PLUGIN_WANT_MIDI_INPUT 1
#define DISTRHO_PLUGIN_WANT_MIDI_OUTPUT 0
#define DISTRHO_PLUGIN_WANT_PROGRAMS 0
#define DISTRHO_PLUGIN_WANT_STATE 0
#define DISTRHO_PLUGIN_WANT_FULL_STATE 0
#define DISTRHO_PLUGIN_WANT_TIMEPOS 0
#define DISTRHO_UI_USE_NANOVG 0
#if defined(CWS80_UI_CAIRO)
#define DISTRHO_UI_USE_CAIRO 1
#endif
#define DISTRHO_UI_USER_RESIZABLE 0
#define DISTRHO_UI_URI DISTRHO_PLUGIN_URI "#UI"
//
#define CWS80_LABEL "CWS80"
#define CWS80_AUTHOR "Jean Pierre Cimalando"
#define CWS80_LICENSE "http://opensource.org/licenses/CECILL-2.1"
#define CWS80_VERSION d_version(1, 0, 0)
#define CWS80_UNIQUE_ID d_cconst('c', 'w', 's', '8')
