/* This file is automatically generated by "generate-parameters.ros". */
#pragma once

namespace cws80 {

#define EACH_PARAMETER(P)                                                               \
    P(0, Env0, L1, x.envs[0].L1, x.envs[0].L1 = v, -64, 63)                             \
    P(1, Env0, L2, x.envs[0].L2, x.envs[0].L2 = v, -64, 63)                             \
    P(2, Env0, L3, x.envs[0].L3, x.envs[0].L3 = v, -64, 63)                             \
    P(3, Env0, T1, x.envs[0].T1, x.envs[0].T1 = v, 0, 63)                               \
    P(4, Env0, T2, x.envs[0].T2, x.envs[0].T2 = v, 0, 63)                               \
    P(5, Env0, T3, x.envs[0].T3, x.envs[0].T3 = v, 0, 63)                               \
    P(6, Env0, T4, x.envs[0].T4, x.envs[0].T4 = v, 0, 63)                               \
    P(7, Env0, LV, x.envs[0].LV, x.envs[0].LV = v, 0, 63)                               \
    P(8, Env0, T1V, x.envs[0].T1V, x.envs[0].T1V = v, 0, 63)                            \
    P(9, Env0, TK, x.envs[0].TK, x.envs[0].TK = v, 0, 63)                               \
    P(10, Env0, LE, x.envs[0].LE, x.envs[0].LE = v, 0, 1)                               \
    P(11, Env0, R2, x.envs[0].R2, x.envs[0].R2 = v, 0, 1)                               \
    P(12, Env1, L1, x.envs[1].L1, x.envs[1].L1 = v, -64, 63)                            \
    P(13, Env1, L2, x.envs[1].L2, x.envs[1].L2 = v, -64, 63)                            \
    P(14, Env1, L3, x.envs[1].L3, x.envs[1].L3 = v, -64, 63)                            \
    P(15, Env1, T1, x.envs[1].T1, x.envs[1].T1 = v, 0, 63)                              \
    P(16, Env1, T2, x.envs[1].T2, x.envs[1].T2 = v, 0, 63)                              \
    P(17, Env1, T3, x.envs[1].T3, x.envs[1].T3 = v, 0, 63)                              \
    P(18, Env1, T4, x.envs[1].T4, x.envs[1].T4 = v, 0, 63)                              \
    P(19, Env1, LV, x.envs[1].LV, x.envs[1].LV = v, 0, 63)                              \
    P(20, Env1, T1V, x.envs[1].T1V, x.envs[1].T1V = v, 0, 63)                           \
    P(21, Env1, TK, x.envs[1].TK, x.envs[1].TK = v, 0, 63)                              \
    P(22, Env1, LE, x.envs[1].LE, x.envs[1].LE = v, 0, 1)                               \
    P(23, Env1, R2, x.envs[1].R2, x.envs[1].R2 = v, 0, 1)                               \
    P(24, Env2, L1, x.envs[2].L1, x.envs[2].L1 = v, -64, 63)                            \
    P(25, Env2, L2, x.envs[2].L2, x.envs[2].L2 = v, -64, 63)                            \
    P(26, Env2, L3, x.envs[2].L3, x.envs[2].L3 = v, -64, 63)                            \
    P(27, Env2, T1, x.envs[2].T1, x.envs[2].T1 = v, 0, 63)                              \
    P(28, Env2, T2, x.envs[2].T2, x.envs[2].T2 = v, 0, 63)                              \
    P(29, Env2, T3, x.envs[2].T3, x.envs[2].T3 = v, 0, 63)                              \
    P(30, Env2, T4, x.envs[2].T4, x.envs[2].T4 = v, 0, 63)                              \
    P(31, Env2, LV, x.envs[2].LV, x.envs[2].LV = v, 0, 63)                              \
    P(32, Env2, T1V, x.envs[2].T1V, x.envs[2].T1V = v, 0, 63)                           \
    P(33, Env2, TK, x.envs[2].TK, x.envs[2].TK = v, 0, 63)                              \
    P(34, Env2, LE, x.envs[2].LE, x.envs[2].LE = v, 0, 1)                               \
    P(35, Env2, R2, x.envs[2].R2, x.envs[2].R2 = v, 0, 1)                               \
    P(36, Env3, L1, x.envs[3].L1, x.envs[3].L1 = v, -64, 63)                            \
    P(37, Env3, L2, x.envs[3].L2, x.envs[3].L2 = v, -64, 63)                            \
    P(38, Env3, L3, x.envs[3].L3, x.envs[3].L3 = v, -64, 63)                            \
    P(39, Env3, T1, x.envs[3].T1, x.envs[3].T1 = v, 0, 63)                              \
    P(40, Env3, T2, x.envs[3].T2, x.envs[3].T2 = v, 0, 63)                              \
    P(41, Env3, T3, x.envs[3].T3, x.envs[3].T3 = v, 0, 63)                              \
    P(42, Env3, T4, x.envs[3].T4, x.envs[3].T4 = v, 0, 63)                              \
    P(43, Env3, LV, x.envs[3].LV, x.envs[3].LV = v, 0, 63)                              \
    P(44, Env3, T1V, x.envs[3].T1V, x.envs[3].T1V = v, 0, 63)                           \
    P(45, Env3, TK, x.envs[3].TK, x.envs[3].TK = v, 0, 63)                              \
    P(46, Env3, LE, x.envs[3].LE, x.envs[3].LE = v, 0, 1)                               \
    P(47, Env3, R2, x.envs[3].R2, x.envs[3].R2 = v, 0, 1)                               \
    P(48, Lfo0, FREQ, x.lfos[0].FREQ, x.lfos[0].FREQ = v, 0, 63)                        \
    P(49, Lfo0, WAV, x.lfos[0].WAV, x.lfos[0].WAV = v, 0, 3)                            \
    P(50, Lfo0, L1, x.lfos[0].L1, x.lfos[0].L1 = v, 0, 63)                              \
    P(51, Lfo0, L2, x.lfos[0].L2, x.lfos[0].L2 = v, 0, 63)                              \
    P(52, Lfo0, MOD, x.lfos[0].MOD(), x.lfos[0].MOD(v), 0, 15)                          \
    P(53, Lfo0, DELAY, x.lfos[0].DELAY, x.lfos[0].DELAY = v, 0, 63)                     \
    P(54, Lfo0, HUMAN, x.lfos[0].HUMAN, x.lfos[0].HUMAN = v, 0, 1)                      \
    P(55, Lfo0, RESET, x.lfos[0].RESET, x.lfos[0].RESET = v, 0, 1)                      \
    P(56, Lfo1, FREQ, x.lfos[1].FREQ, x.lfos[1].FREQ = v, 0, 63)                        \
    P(57, Lfo1, WAV, x.lfos[1].WAV, x.lfos[1].WAV = v, 0, 3)                            \
    P(58, Lfo1, L1, x.lfos[1].L1, x.lfos[1].L1 = v, 0, 63)                              \
    P(59, Lfo1, L2, x.lfos[1].L2, x.lfos[1].L2 = v, 0, 63)                              \
    P(60, Lfo1, MOD, x.lfos[1].MOD(), x.lfos[1].MOD(v), 0, 15)                          \
    P(61, Lfo1, DELAY, x.lfos[1].DELAY, x.lfos[1].DELAY = v, 0, 63)                     \
    P(62, Lfo1, HUMAN, x.lfos[1].HUMAN, x.lfos[1].HUMAN = v, 0, 1)                      \
    P(63, Lfo1, RESET, x.lfos[1].RESET, x.lfos[1].RESET = v, 0, 1)                      \
    P(64, Lfo2, FREQ, x.lfos[2].FREQ, x.lfos[2].FREQ = v, 0, 63)                        \
    P(65, Lfo2, WAV, x.lfos[2].WAV, x.lfos[2].WAV = v, 0, 3)                            \
    P(66, Lfo2, L1, x.lfos[2].L1, x.lfos[2].L1 = v, 0, 63)                              \
    P(67, Lfo2, L2, x.lfos[2].L2, x.lfos[2].L2 = v, 0, 63)                              \
    P(68, Lfo2, MOD, x.lfos[2].MOD(), x.lfos[2].MOD(v), 0, 15)                          \
    P(69, Lfo2, DELAY, x.lfos[2].DELAY, x.lfos[2].DELAY = v, 0, 63)                     \
    P(70, Lfo2, HUMAN, x.lfos[2].HUMAN, x.lfos[2].HUMAN = v, 0, 1)                      \
    P(71, Lfo2, RESET, x.lfos[2].RESET, x.lfos[2].RESET = v, 0, 1)                      \
    P(72, Osc0, OCT, x.oscs[0].OCT(), x.oscs[0].OCT(v), -3, 5)                          \
    P(73, Osc0, SEMI, x.oscs[0].SEMI(), x.oscs[0].SEMI(v), 0, 11)                       \
    P(74, Osc0, FINE, x.oscs[0].FINE, x.oscs[0].FINE = v, 0, 31)                        \
    P(75, Osc0, FMSRC1, x.oscs[0].FMSRC1, x.oscs[0].FMSRC1 = v, 0, 15)                  \
    P(76, Osc0, FMSRC2, x.oscs[0].FMSRC2, x.oscs[0].FMSRC2 = v, 0, 15)                  \
    P(77, Osc0, FCMODAMT1, x.oscs[0].FCMODAMT1, x.oscs[0].FCMODAMT1 = v, -64, 63)       \
    P(78, Osc0, FCMODAMT2, x.oscs[0].FCMODAMT2, x.oscs[0].FCMODAMT2 = v, -64, 63)       \
    P(79, Osc0, WAVEFORM, x.oscs[0].WAVEFORM, x.oscs[0].WAVEFORM = v, 0, 255)           \
    P(80, Osc0, DCALEVEL, x.oscs[0].DCALEVEL, x.oscs[0].DCALEVEL = v, 0, 63)            \
    P(81, Osc0, DCAENABLE, x.oscs[0].DCAENABLE, x.oscs[0].DCAENABLE = v, 0, 1)          \
    P(82, Osc0, AMSRC1, x.oscs[0].AMSRC1, x.oscs[0].AMSRC1 = v, 0, 15)                  \
    P(83, Osc0, AMSRC2, x.oscs[0].AMSRC2, x.oscs[0].AMSRC2 = v, 0, 15)                  \
    P(84, Osc0, AMAMT1, x.oscs[0].AMAMT1, x.oscs[0].AMAMT1 = v, -64, 63)                \
    P(85, Osc0, AMAMT2, x.oscs[0].AMAMT2, x.oscs[0].AMAMT2 = v, -64, 63)                \
    P(86, Osc1, OCT, x.oscs[1].OCT(), x.oscs[1].OCT(v), -3, 5)                          \
    P(87, Osc1, SEMI, x.oscs[1].SEMI(), x.oscs[1].SEMI(v), 0, 11)                       \
    P(88, Osc1, FINE, x.oscs[1].FINE, x.oscs[1].FINE = v, 0, 31)                        \
    P(89, Osc1, FMSRC1, x.oscs[1].FMSRC1, x.oscs[1].FMSRC1 = v, 0, 15)                  \
    P(90, Osc1, FMSRC2, x.oscs[1].FMSRC2, x.oscs[1].FMSRC2 = v, 0, 15)                  \
    P(91, Osc1, FCMODAMT1, x.oscs[1].FCMODAMT1, x.oscs[1].FCMODAMT1 = v, -64, 63)       \
    P(92, Osc1, FCMODAMT2, x.oscs[1].FCMODAMT2, x.oscs[1].FCMODAMT2 = v, -64, 63)       \
    P(93, Osc1, WAVEFORM, x.oscs[1].WAVEFORM, x.oscs[1].WAVEFORM = v, 0, 255)           \
    P(94, Osc1, DCALEVEL, x.oscs[1].DCALEVEL, x.oscs[1].DCALEVEL = v, 0, 63)            \
    P(95, Osc1, DCAENABLE, x.oscs[1].DCAENABLE, x.oscs[1].DCAENABLE = v, 0, 1)          \
    P(96, Osc1, AMSRC1, x.oscs[1].AMSRC1, x.oscs[1].AMSRC1 = v, 0, 15)                  \
    P(97, Osc1, AMSRC2, x.oscs[1].AMSRC2, x.oscs[1].AMSRC2 = v, 0, 15)                  \
    P(98, Osc1, AMAMT1, x.oscs[1].AMAMT1, x.oscs[1].AMAMT1 = v, -64, 63)                \
    P(99, Osc1, AMAMT2, x.oscs[1].AMAMT2, x.oscs[1].AMAMT2 = v, -64, 63)                \
    P(100, Osc2, OCT, x.oscs[2].OCT(), x.oscs[2].OCT(v), -3, 5)                         \
    P(101, Osc2, SEMI, x.oscs[2].SEMI(), x.oscs[2].SEMI(v), 0, 11)                      \
    P(102, Osc2, FINE, x.oscs[2].FINE, x.oscs[2].FINE = v, 0, 31)                       \
    P(103, Osc2, FMSRC1, x.oscs[2].FMSRC1, x.oscs[2].FMSRC1 = v, 0, 15)                 \
    P(104, Osc2, FMSRC2, x.oscs[2].FMSRC2, x.oscs[2].FMSRC2 = v, 0, 15)                 \
    P(105, Osc2, FCMODAMT1, x.oscs[2].FCMODAMT1, x.oscs[2].FCMODAMT1 = v, -64, 63)      \
    P(106, Osc2, FCMODAMT2, x.oscs[2].FCMODAMT2, x.oscs[2].FCMODAMT2 = v, -64, 63)      \
    P(107, Osc2, WAVEFORM, x.oscs[2].WAVEFORM, x.oscs[2].WAVEFORM = v, 0, 255)          \
    P(108, Osc2, DCALEVEL, x.oscs[2].DCALEVEL, x.oscs[2].DCALEVEL = v, 0, 63)           \
    P(109, Osc2, DCAENABLE, x.oscs[2].DCAENABLE, x.oscs[2].DCAENABLE = v, 0, 1)         \
    P(110, Osc2, AMSRC1, x.oscs[2].AMSRC1, x.oscs[2].AMSRC1 = v, 0, 15)                 \
    P(111, Osc2, AMSRC2, x.oscs[2].AMSRC2, x.oscs[2].AMSRC2 = v, 0, 15)                 \
    P(112, Osc2, AMAMT1, x.oscs[2].AMAMT1, x.oscs[2].AMAMT1 = v, -64, 63)               \
    P(113, Osc2, AMAMT2, x.oscs[2].AMAMT2, x.oscs[2].AMAMT2 = v, -64, 63)               \
    P(114, Misc, DCA4MODAMT, x.misc.DCA4MODAMT, x.misc.DCA4MODAMT = v, 0, 63)           \
    P(115, Misc, AM, x.misc.AM, x.misc.AM = v, 0, 1)                                    \
    P(116, Misc, FLTFC, x.misc.FLTFC, x.misc.FLTFC = v, 0, 127)                         \
    P(117, Misc, SYNC, x.misc.SYNC, x.misc.SYNC = v, 0, 1)                              \
    P(118, Misc, Q, x.misc.Q, x.misc.Q = v, 0, 31)                                      \
    P(119, Misc, FCSRC1, x.misc.FCSRC1, x.misc.FCSRC1 = v, 0, 15)                       \
    P(120, Misc, FCSRC2, x.misc.FCSRC2, x.misc.FCSRC2 = v, 0, 15)                       \
    P(121, Misc, FCMODAMT1, x.misc.FCMODAMT1, x.misc.FCMODAMT1 = v, -64, 63)            \
    P(122, Misc, VC, x.misc.VC, x.misc.VC = v, 0, 1)                                    \
    P(123, Misc, FCMODAMT2, x.misc.FCMODAMT2, x.misc.FCMODAMT2 = v, -64, 63)            \
    P(124, Misc, MONO, x.misc.MONO, x.misc.MONO = v, 0, 1)                              \
    P(125, Misc, KEYBD, x.misc.KEYBD, x.misc.KEYBD = v, 0, 63)                          \
    P(126, Misc, ENV, x.misc.ENV, x.misc.ENV = v, 0, 1)                                 \
    P(127, Misc, GLIDE, x.misc.GLIDE, x.misc.GLIDE = v, 0, 63)                          \
    P(128, Misc, OSC, x.misc.OSC, x.misc.OSC = v, 0, 1)                                 \
    P(129, Misc, SPLITPOINT, x.misc.SPLITPOINT, x.misc.SPLITPOINT = v, 0, 127)          \
    P(130, Misc, SPLITDIR, x.misc.SPLITDIR, x.misc.SPLITDIR = v, 0, 1)                  \
    P(131, Misc, LAYERPRG, x.misc.LAYERPRG, x.misc.LAYERPRG = v, 0, 127)                \
    P(132, Misc, LAYER, x.misc.LAYER, x.misc.LAYER = v, 0, 1)                           \
    P(133, Misc, SPLITPRG, x.misc.SPLITPRG, x.misc.SPLITPRG = v, 0, 127)                \
    P(134, Misc, SPLIT, x.misc.SPLIT, x.misc.SPLIT = v, 0, 1)                           \
    P(135, Misc, SPLITLAYERPRG, x.misc.SPLITLAYERPRG, x.misc.SPLITLAYERPRG = v, 0, 127) \
    P(136, Misc, SPLITLAYER, x.misc.SPLITLAYER, x.misc.SPLITLAYER = v, 0, 1)            \
    P(137, Misc, PANMODSRC, x.misc.PANMODSRC, x.misc.PANMODSRC = v, 0, 15)              \
    P(138, Misc, PAN, x.misc.PAN, x.misc.PAN = v, 0, 15)                                \
    P(139, Misc, PANMODAMT, x.misc.PANMODAMT, x.misc.PANMODAMT = v, -64, 63)            \
    P(140, Misc, CYCLE, x.misc.CYCLE, x.misc.CYCLE = v, 0, 1)                           \
    /* END OF PARAMETERS */

namespace Param {
    enum {
        env_count = 4,
        lfo_count = 3,
        osc_count = 3,
        //
        env_params = 12,
        lfo_params = 8,
        osc_params = 14,
        misc_params = 27,
        //
        num_params = 141,
        //
        first_env_param = 0,
        first_lfo_param = 48,
        first_osc_param = 72,
        first_misc_param = 114,
    };
}  // namespace Param

}  // namespace cws80
